# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meditab/catkin_ws/src/ros_openvslam/openvslam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meditab/catkin_ws/src/ros_openvslam/openvslam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meditab/catkin_ws/src/ros_openvslam/openvslam/CMakeFiles /home/meditab/catkin_ws/src/ros_openvslam/openvslam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meditab/catkin_ws/src/ros_openvslam/openvslam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openvslam

# Build rule for target.
openvslam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvslam
.PHONY : openvslam

# fast build rule for target.
openvslam/fast:
	$(MAKE) -f src/openvslam/CMakeFiles/openvslam.dir/build.make src/openvslam/CMakeFiles/openvslam.dir/build
.PHONY : openvslam/fast

#=============================================================================
# Target rules for targets named pangolin_viewer

# Build rule for target.
pangolin_viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pangolin_viewer
.PHONY : pangolin_viewer

# fast build rule for target.
pangolin_viewer/fast:
	$(MAKE) -f src/pangolin_viewer/CMakeFiles/pangolin_viewer.dir/build.make src/pangolin_viewer/CMakeFiles/pangolin_viewer.dir/build
.PHONY : pangolin_viewer/fast

#=============================================================================
# Target rules for targets named run_video_slam

# Build rule for target.
run_video_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_video_slam
.PHONY : run_video_slam

# fast build rule for target.
run_video_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_video_slam.dir/build.make example/CMakeFiles/run_video_slam.dir/build
.PHONY : run_video_slam/fast

#=============================================================================
# Target rules for targets named run_kitti_slam

# Build rule for target.
run_kitti_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_kitti_slam
.PHONY : run_kitti_slam

# fast build rule for target.
run_kitti_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_kitti_slam.dir/build.make example/CMakeFiles/run_kitti_slam.dir/build
.PHONY : run_kitti_slam/fast

#=============================================================================
# Target rules for targets named run_image_slam

# Build rule for target.
run_image_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_image_slam
.PHONY : run_image_slam

# fast build rule for target.
run_image_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_image_slam.dir/build.make example/CMakeFiles/run_image_slam.dir/build
.PHONY : run_image_slam/fast

#=============================================================================
# Target rules for targets named run_camera_slam

# Build rule for target.
run_camera_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_camera_slam
.PHONY : run_camera_slam

# fast build rule for target.
run_camera_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_camera_slam.dir/build.make example/CMakeFiles/run_camera_slam.dir/build
.PHONY : run_camera_slam/fast

#=============================================================================
# Target rules for targets named run_image_localization

# Build rule for target.
run_image_localization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_image_localization
.PHONY : run_image_localization

# fast build rule for target.
run_image_localization/fast:
	$(MAKE) -f example/CMakeFiles/run_image_localization.dir/build.make example/CMakeFiles/run_image_localization.dir/build
.PHONY : run_image_localization/fast

#=============================================================================
# Target rules for targets named run_camera_localization

# Build rule for target.
run_camera_localization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_camera_localization
.PHONY : run_camera_localization

# fast build rule for target.
run_camera_localization/fast:
	$(MAKE) -f example/CMakeFiles/run_camera_localization.dir/build.make example/CMakeFiles/run_camera_localization.dir/build
.PHONY : run_camera_localization/fast

#=============================================================================
# Target rules for targets named run_video_localization

# Build rule for target.
run_video_localization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_video_localization
.PHONY : run_video_localization

# fast build rule for target.
run_video_localization/fast:
	$(MAKE) -f example/CMakeFiles/run_video_localization.dir/build.make example/CMakeFiles/run_video_localization.dir/build
.PHONY : run_video_localization/fast

#=============================================================================
# Target rules for targets named run_euroc_slam

# Build rule for target.
run_euroc_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_euroc_slam
.PHONY : run_euroc_slam

# fast build rule for target.
run_euroc_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_euroc_slam.dir/build.make example/CMakeFiles/run_euroc_slam.dir/build
.PHONY : run_euroc_slam/fast

#=============================================================================
# Target rules for targets named run_tum_rgbd_slam

# Build rule for target.
run_tum_rgbd_slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tum_rgbd_slam
.PHONY : run_tum_rgbd_slam

# fast build rule for target.
run_tum_rgbd_slam/fast:
	$(MAKE) -f example/CMakeFiles/run_tum_rgbd_slam.dir/build.make example/CMakeFiles/run_tum_rgbd_slam.dir/build
.PHONY : run_tum_rgbd_slam/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... openvslam"
	@echo "... pangolin_viewer"
	@echo "... run_video_slam"
	@echo "... run_kitti_slam"
	@echo "... run_image_slam"
	@echo "... run_camera_slam"
	@echo "... run_image_localization"
	@echo "... run_camera_localization"
	@echo "... run_video_localization"
	@echo "... run_euroc_slam"
	@echo "... run_tum_rgbd_slam"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

